name: Deploy Front to GitHub Pages

on:
  push:
    branches:
      - main  # Or your working branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front  # Ensure npm commands are run inside the 'front' directory

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (with cache clearing)
        run: |
          rm -rf node_modules
          npm install

      - name: List available npm scripts (Debugging)
        run: npm run

      - name: Build frontend
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git -c user.name="github-actions" -c user.email="github-actions@github.com" commit -m "Deploy to GitHub Pages"
          npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
